### ISSUE TITLE
New account: Open Tree of Life

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#221]
EZID prefix/shoulder: doi:10.48699/T9
Account name: Open Tree of Life
Datacenter: CDL.UCM

#Tasks & steps

- [x] Request new prefix from DataCite

- [x] Create new shoulder

- [x] Add shoulder to group

- [x] Create new user

- [x] Add user to group

- [x] Give user access to shoulder

- [x] Send onboarding email to user

- [x] Add user to email list
