### ISSUE TITLE
New account: Archaeological Research Facility (DOIS and ARKS)

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid-service#258]
EZID prefix/shoulder: 
Account name: Archaeological Research Facility
Datacenter: CDL.UCB

#Tasks & steps

- [x]     Request new prefix from DataCite
- [x]     Create new shoulder
- [x]     Add shoulder to group
- [x]     Create new user
- [x]     Add user to group
- [x]     Give user access to shoulder
- [x]     Send onboarding email to user
- [x]     Add user to email list

**Comment by adambuttrick** [comment]
NAAN/shoulder: 
Account name: Archaeological Research Facility
Acronym: ARF

#Tasks & steps

- [x]    Request NAAN 
- [x]     Create new shoulder
- [x]     Add shoulder to group
- [x]     Create new user
- [x]     Add user to group
- [x]     Give user access to shoulder
- [ ]     Send onboarding email to user
- [ ]     Add user to email list

**Comment by adambuttrick** [comment]
New DOI Prefix from DataCite: 10.60639
NAAN: 44124
