### ISSUE TITLE
New Crossref shoulders for eScholarship 10.5070 prefix

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#74]
We need to set up 11 new Crossref-enabled shoulders (1 per campus, plus CDL) to register eScholarship content. Shoulders will use the existing Crossref prefix 10.5070. 

- [ ] CDL/Cross-campus eScholarship (cdl-eschol): 10.5070/C2

- [ ] UC Berkeley eScholarship (ucb-eschol): 10.5070/B2

- [ ] UC Davis eScholarship (ucd-eschol): 10.5070/D2

- [ ] UC Irvine eScholarship (uci-eschol): 10.5070/VN2

- [ ] UCLA eScholarship (ucla-eschol): 10.5070/LX2 

- [ ] UC Merced eScholarship (ucm-eschol): 10.5070/M2

- [ ] UC Riverside eScholarship (ucr-eschol): 10.5070/R2

- [ ] UC Santa Barbara eScholarship (sb-eschol): 10.5070/SB2

- [ ] UC Santa Cruz eScholarship (ucsc-eschol): 10.5070/SC2

- [ ] UC San Diego eScholarship (ucsd_eschol): 10.5070/SD2

- [ ] UCSF eScholarship (ucsf-eschol): 10.5070/SF2
